enum MainPanelDataType {
  LayerImages = "LAYER_IMAGES",
  CollectionPreview = "COLLECTION_PREVIEW",
  Open = "OPEN",
  DeleteCollection = "DELETE_COLLECTION",
  DeleteLayer = "DELETE_LAYER",
  EditForm = "EDIT_FORM",
  ShowCollectionDetails = "SHOW_DETAILS",
  Deleted = "DELETED",
  EditCollectionFormFromAsside = "EDIT_FORM",
  ShowLayerEditForm = "SHOW_LAYER_EDIT_FORM",
  EditImage = "EDIT_IMAGE",
  CancelEditImage = "CANCEL_EDIT_IMAGE",
  CloseDownloadButton = "CLOSE_DOWNLOAD_BUTTON",
  ShowDownloadButton = "SHOW_DOWNLOAD_BUTTON",
  ShowCreateNewLayerForm = "SHOW_CREATE_NEW_LAYER_FORM",
  CloseCreateNewLayerForm = "CLOSE_CREATE_NEW_LAYER_FORM",
  ShowLoginForm = "SHOW_LOGIN_FORM",
  HideLoginForm = "HIDE_LOGIN_FORM",
  ShowPaymentNotification = "SHOW_PAYMENT_NOTIFICATION",
  ClosePaymentNotification = "CLOSE_PAYMENT_NOTIFICATION",
  ShowPaymentForm = "SHOW_PAYMENT_FORM",
  ClosePaymentForm = "CLOSE_PAYMENT_FORM",
}

export default MainPanelDataType;
